event_inherited();
persist = true;
hp = 1;
damage_set(2, 4, 6);
damageable = false;
blocking = false;
shot_type = 0;
phy_type = phy_types.NEW;
through_walls = true;
grav = 0;
abs_hspeed = 5;
dest_x = 0;
limit_x = [0, 1000];
animation_add("S", keyframes_generate(3, 1));
animation_play("S");