event_inherited();
hp = 1;
grav = 0;
persist = true;
collide_damage = 0;
shot_type = 0;
phy_type = phy_types.NEW;
through_walls = false;
animation_add("S", keyframes_generate(image_number, 1));
animation_play("S");
owner = noone;
started = false;