event_inherited();
animation_add("L", keyframes_generate(image_number, 1 / 4));
animation_add_loop("L");
animation_play("L");
amount = 1;
pickup_type = pickup_types.lifeup;
sound = snd_item_lifeup;
palette_init();
mask_index = spr_square_16;
physics_ignore_frame = 1;
event_perform(ev_step, ev_step_normal);