event_inherited();
sound = snd_player_axl_bullets;
execute_step_in_first_frame = true;
timer = -1;
atk = 0.75;
abs_hspeed = 4;
animation_auto = false;
boss_buffer_limit = 25;
animation_auto = false;
abs_max_speed = 6.25;