animation_init();
animations_init();
is_temporary = false;
target = noone;
pickup_pause = true;
blink_limit = 60;
timer_limit = 270;
timer = 0;
amount = 1;
time_per_unit = 4;
wait_limit = 0;
min_limit = 0;
bar_light = false;
sound = noone;
grav_default = 0.25;
heart_id = -1;
is_player = false;
inside_view = false;
global.items_count++;
scr_physics_init(grav_default, 0, 0);
local_game_speed_init();