{
  "bboxMode": 0,
  "collisionKind": 1,
  "type": 0,
  "origin": 0,
  "preMultiplyAlpha": false,
  "edgeFiltering": false,
  "collisionTolerance": 0,
  "swfPrecision": 2.525,
  "bbox_left": 0,
  "bbox_right": 319,
  "bbox_top": 0,
  "bbox_bottom": 239,
  "HTile": false,
  "VTile": false,
  "For3D": false,
  "width": 320,
  "height": 240,
  "textureGroupId": {
    "name": "Default",
    "path": "texturegroups/Default",
  },
  "swatchColours": null,
  "gridX": 0,
  "gridY": 0,
  "frames": [
    {"compositeImage":{"FrameId":{"name":"0805d88d-fdb5-4e21-84b8-a86146088ffb","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"0805d88d-fdb5-4e21-84b8-a86146088ffb","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"0805d88d-fdb5-4e21-84b8-a86146088ffb","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"af644d30-39af-4ea7-b46c-e4aadcb5ea23","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"af644d30-39af-4ea7-b46c-e4aadcb5ea23","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"af644d30-39af-4ea7-b46c-e4aadcb5ea23","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f146e6e2-a55b-4c28-bedc-510bbfebb9d5","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f146e6e2-a55b-4c28-bedc-510bbfebb9d5","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"f146e6e2-a55b-4c28-bedc-510bbfebb9d5","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"2f979ba7-82fc-4cfc-a7e3-05a42e0ca0de","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"2f979ba7-82fc-4cfc-a7e3-05a42e0ca0de","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"2f979ba7-82fc-4cfc-a7e3-05a42e0ca0de","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"688ce1fd-8029-4a24-b782-c47df2a5ccc3","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"688ce1fd-8029-4a24-b782-c47df2a5ccc3","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"688ce1fd-8029-4a24-b782-c47df2a5ccc3","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"57390c5c-a237-41ac-8437-e4b24a8aba39","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"57390c5c-a237-41ac-8437-e4b24a8aba39","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"57390c5c-a237-41ac-8437-e4b24a8aba39","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d53f4df7-f39e-44cb-bff5-522721b64222","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d53f4df7-f39e-44cb-bff5-522721b64222","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"d53f4df7-f39e-44cb-bff5-522721b64222","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"324c47d5-2396-4609-b153-a5db155aaf46","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"324c47d5-2396-4609-b153-a5db155aaf46","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"324c47d5-2396-4609-b153-a5db155aaf46","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"061ef11f-3a2e-474e-82a5-0302f56f8506","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"061ef11f-3a2e-474e-82a5-0302f56f8506","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"061ef11f-3a2e-474e-82a5-0302f56f8506","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d184e9cd-e0e0-48ee-a687-a324d438cf34","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d184e9cd-e0e0-48ee-a687-a324d438cf34","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"d184e9cd-e0e0-48ee-a687-a324d438cf34","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"6daedab7-5eb2-49ff-8ab8-b7086935a68a","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"6daedab7-5eb2-49ff-8ab8-b7086935a68a","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"6daedab7-5eb2-49ff-8ab8-b7086935a68a","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"61656d9d-550a-4308-9e0b-d83c020fb26f","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"61656d9d-550a-4308-9e0b-d83c020fb26f","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"61656d9d-550a-4308-9e0b-d83c020fb26f","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a191e78f-0815-440b-a095-8c2a2c56d035","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a191e78f-0815-440b-a095-8c2a2c56d035","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"a191e78f-0815-440b-a095-8c2a2c56d035","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c8680837-4f38-47a5-9970-c0b176f66ae4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c8680837-4f38-47a5-9970-c0b176f66ae4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"c8680837-4f38-47a5-9970-c0b176f66ae4","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"667ab55e-ee8a-4102-a826-4ae196b76944","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"667ab55e-ee8a-4102-a826-4ae196b76944","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"667ab55e-ee8a-4102-a826-4ae196b76944","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c65616a0-4322-4382-bd46-09a5ce34ca73","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c65616a0-4322-4382-bd46-09a5ce34ca73","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"c65616a0-4322-4382-bd46-09a5ce34ca73","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"ebaeddb1-d441-484c-b67f-ec279cbf5646","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"ebaeddb1-d441-484c-b67f-ec279cbf5646","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"ebaeddb1-d441-484c-b67f-ec279cbf5646","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"fef38e64-61ae-4d0d-8e96-ae4772469453","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"fef38e64-61ae-4d0d-8e96-ae4772469453","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"fef38e64-61ae-4d0d-8e96-ae4772469453","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"4e917de7-bc30-4fc9-ab9d-ce575c01c063","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"4e917de7-bc30-4fc9-ab9d-ce575c01c063","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"4e917de7-bc30-4fc9-ab9d-ce575c01c063","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"84d5328e-88b2-4694-9d27-a5f69235f023","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"84d5328e-88b2-4694-9d27-a5f69235f023","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"84d5328e-88b2-4694-9d27-a5f69235f023","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7edf98a6-fd3a-4009-bb26-1467b6ec974e","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7edf98a6-fd3a-4009-bb26-1467b6ec974e","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"7edf98a6-fd3a-4009-bb26-1467b6ec974e","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"8a4c3cee-9959-444c-be5c-56f3879be4e4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"8a4c3cee-9959-444c-be5c-56f3879be4e4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"8a4c3cee-9959-444c-be5c-56f3879be4e4","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c7608e5b-40ea-4f41-a24d-1cb519b3b831","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c7608e5b-40ea-4f41-a24d-1cb519b3b831","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"c7608e5b-40ea-4f41-a24d-1cb519b3b831","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c4c46b6b-c096-49af-85a7-ae6e9d1a9e8c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c4c46b6b-c096-49af-85a7-ae6e9d1a9e8c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"c4c46b6b-c096-49af-85a7-ae6e9d1a9e8c","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"898721f4-2a40-49c8-aba9-8c412675bb1c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"898721f4-2a40-49c8-aba9-8c412675bb1c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"898721f4-2a40-49c8-aba9-8c412675bb1c","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"62ce0f0b-e744-40a4-8a36-c156486d3f67","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"62ce0f0b-e744-40a4-8a36-c156486d3f67","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"62ce0f0b-e744-40a4-8a36-c156486d3f67","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"474918da-5286-451c-a3d0-480faf4bb6dd","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"474918da-5286-451c-a3d0-480faf4bb6dd","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"474918da-5286-451c-a3d0-480faf4bb6dd","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"4937e80b-feb7-47d1-a3f7-2135dce89aa0","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"4937e80b-feb7-47d1-a3f7-2135dce89aa0","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"LayerId":{"name":"46379137-ae17-4613-bb44-6243b31aae7b","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","name":"4937e80b-feb7-47d1-a3f7-2135dce89aa0","tags":[],"resourceType":"GMSpriteFrame",},
  ],
  "sequence": {
    "spriteId": {"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},
    "timeUnits": 1,
    "playback": 1,
    "playbackSpeed": 12.0,
    "playbackSpeedType": 0,
    "autoRecord": true,
    "volume": 1.0,
    "length": 28.0,
    "events": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MessageEventKeyframe>",},
    "moments": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MomentsEventKeyframe>",},
    "tracks": [
      {"name":"frames","spriteId":null,"keyframes":{"Keyframes":[
            {"id":"ca07128a-1d25-4f0b-bdc4-86108f7ff715","Key":0.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"0805d88d-fdb5-4e21-84b8-a86146088ffb","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"e25e4786-cebf-413c-b1a3-5055831da37a","Key":1.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"af644d30-39af-4ea7-b46c-e4aadcb5ea23","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"8b52737a-2c0d-4993-b60e-2c073fc7addf","Key":2.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f146e6e2-a55b-4c28-bedc-510bbfebb9d5","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d50a9f57-79a6-4038-82dd-bde0b9d5ed23","Key":3.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"2f979ba7-82fc-4cfc-a7e3-05a42e0ca0de","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c6b116e0-134f-4016-aa51-84178b081f30","Key":4.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"688ce1fd-8029-4a24-b782-c47df2a5ccc3","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d5a15d32-50b8-487c-b333-fcb464ed9f13","Key":5.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"57390c5c-a237-41ac-8437-e4b24a8aba39","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"bc0d3f90-23d9-4d41-8578-ab10c080d9ca","Key":6.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d53f4df7-f39e-44cb-bff5-522721b64222","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c507710d-31e9-44de-828f-6f8099b1c6bb","Key":7.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"324c47d5-2396-4609-b153-a5db155aaf46","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"515c9071-9d56-49af-9a8a-70bc80db9586","Key":8.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"061ef11f-3a2e-474e-82a5-0302f56f8506","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2d8a8cb8-cdbb-4815-b543-89db94db36e2","Key":9.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d184e9cd-e0e0-48ee-a687-a324d438cf34","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d695c1b8-5172-4fcc-ae9d-232dff0f8bbe","Key":10.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"6daedab7-5eb2-49ff-8ab8-b7086935a68a","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4d05249d-5397-4ca4-8992-3a6abebcb99f","Key":11.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"61656d9d-550a-4308-9e0b-d83c020fb26f","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4fd45f5c-3a9c-4f5c-9e4a-6fa26d7bae6c","Key":12.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a191e78f-0815-440b-a095-8c2a2c56d035","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c698b25e-c198-425a-b46d-153fc05c77aa","Key":13.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c8680837-4f38-47a5-9970-c0b176f66ae4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"fcabf510-1edf-4718-943c-3699fb2bf2e4","Key":14.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"667ab55e-ee8a-4102-a826-4ae196b76944","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"b939520f-33e2-430b-8afe-d13c55b6442d","Key":15.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c65616a0-4322-4382-bd46-09a5ce34ca73","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9e1985e1-1210-4ca2-a04e-f969561944af","Key":16.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"ebaeddb1-d441-484c-b67f-ec279cbf5646","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"065614ac-c41d-438c-afbb-74280db31027","Key":17.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"fef38e64-61ae-4d0d-8e96-ae4772469453","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"42dedf9e-9890-4991-9a71-9bcfedc7db87","Key":18.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"4e917de7-bc30-4fc9-ab9d-ce575c01c063","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"55a1e12d-9cc9-4b88-9b30-fe04dfead09c","Key":19.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"84d5328e-88b2-4694-9d27-a5f69235f023","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4b64b65b-f9b6-4398-980f-7f54361ec7c4","Key":20.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7edf98a6-fd3a-4009-bb26-1467b6ec974e","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"6b8d544f-8f99-44d2-be4e-5d361f8813e7","Key":21.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"8a4c3cee-9959-444c-be5c-56f3879be4e4","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"956f9445-e349-4353-a8bd-5b85c6209ea8","Key":22.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c7608e5b-40ea-4f41-a24d-1cb519b3b831","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"838fd023-005f-4f07-b36a-36d58037407d","Key":23.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c4c46b6b-c096-49af-85a7-ae6e9d1a9e8c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9cec7115-85f7-43c0-b240-f288206ac3eb","Key":24.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"898721f4-2a40-49c8-aba9-8c412675bb1c","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"12d370e5-0953-4699-90a0-d297c4c96376","Key":25.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"62ce0f0b-e744-40a4-8a36-c156486d3f67","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"862c3daa-dc23-49de-8cf4-89daf4dd06fa","Key":26.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"474918da-5286-451c-a3d0-480faf4bb6dd","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"55b947dd-78ef-404b-81f8-15b759465e98","Key":27.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"4937e80b-feb7-47d1-a3f7-2135dce89aa0","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
          ],"resourceVersion":"1.0","resourceType":"KeyframeStore<SpriteFrameKeyframe>",},"trackColour":0,"inheritsTrackColour":true,"builtinName":0,"traits":0,"interpolation":1,"tracks":[],"events":[],"isCreationTrack":false,"resourceVersion":"1.0","tags":[],"resourceType":"GMSpriteFramesTrack","modifiers":[],},
    ],
    "visibleRange": {"x":0.0,"y":0.0,},
    "lockOrigin": false,
    "showBackdrop": true,
    "showBackdropImage": false,
    "backdropImagePath": "",
    "backdropImageOpacity": 0.5,
    "backdropWidth": 1920,
    "backdropHeight": 1080,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "xorigin": 0,
    "yorigin": 0,
    "eventToFunction": {},
    "eventStubScript": null,
    "parent": {"name":"spr_magma_dragoon_raging_background","path":"sprites/spr_magma_dragoon_raging_background/spr_magma_dragoon_raging_background.yy",},
    "resourceVersion": "1.4",
    "name": "",
    "tags": [],
    "resourceType": "GMSequence",
  },
  "layers": [
    {"visible":true,"isLocked":false,"blendMode":0,"opacity":100.0,"displayName":"default","resourceVersion":"1.0","name":"46379137-ae17-4613-bb44-6243b31aae7b","tags":[],"resourceType":"GMImageLayer",},
  ],
  "nineSlice": null,
  "parent": {
    "name": "Magma Dragoon",
    "path": "folders/Sprites/Maverick/Bosses/Magma Dragoon.yy",
  },
  "resourceVersion": "1.0",
  "name": "spr_magma_dragoon_raging_background",
  "tags": [],
  "resourceType": "GMSprite",
}