event_inherited();
hp = 1;
grav = 0;
damage_set(2, 4, 6);
damageable = true;
blocking = array_get([0, 1, 1], global.difficulty);
abs_hspeed = array_get([4, 8, 10], global.difficulty);
angle_types = 0;
phy_type = phy_types.NEW;
through_walls = true;
audio_play(snd_ice_shot);